services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: langchain_user
      POSTGRES_PASSWORD: langchain_pass
      POSTGRES_DB: langchain_db
    volumes:
      - "./docker/volumes/postgresql:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080