POST http://127.0.0.1:8000/ask
Content-Type: application/json

{
  "query": "si cual es el stock",
  "session_id": "f47ac10b-58cc-4372-a567-0e02b2c3d472"
}

### History Request
POST http://127.0.0.1:8000/history
Content-Type: application/json

{
  "session_id": "b96c8d11-ffb3-47a0-9346-f79257f64844"
}

### obtener info del vendedor
GET http://127.0.0.1:8000/vendedores_profile/785840b0-7d4e-45de-abb1-d6265b30bab8
